### ISSUE TITLE
Not working topscroller

### ISSUE THREAD

**Issue by Sagamang** [ladmerc/ionic-topscroller#1]
Hi,

I tried to implement the topscroller in my project. 
But I cant seem to get it working.
Moreover, I dont even see the floating button. 

Can you help me out?

Kind regards,
Sagar

**Comment by ladmerc** [comment]
Hello, 

What specific error are you getting? The floating button is hidden by default. I'll make a codepen today and paste here.

**Comment by Sagamang** [comment]
Hi Meka Ladna,

First of all I want to thank you by providing others with such an example
as yours.
On the screen were I assigned the controller to I can not scroll anymore.
The button is vissible when I enter the screen  (Which should not be
vissible when entering the screen of course).
_In addition_, I work with tabs that I hide for my pages. However since
implementing the controller and directives as you said I also see the tabs.

page were I attached the topscroller controller
[image: Inline afbeelding 5]
Home page
[image: Inline afbeelding 4]
Other page
[image: Inline afbeelding 6]

in my console I can see the following errors:

ionic.bundle.js:18891 Error: [$injector:unpr] Unknown provider:
$elementProvider <- $element
http://errors.angularjs.org/1.2.17/$injector/unpr?p0=%24elementProvider%20%3C-%20%24element
    at ionic.bundle.js:9070
    at ionic.bundle.js:12727
    at Object.getService [as get](ionic.bundle.js:12854)
    at ionic.bundle.js:12732
    at getService (ionic.bundle.js:12854)
    at invoke (ionic.bundle.js:12881)
    at Object.instantiate (ionic.bundle.js:12902)
    at ionic.bundle.js:16156
    at updateView (ionic.bundle.js:42695)
    at eventHook (ionic.bundle.js:42642)(anonymous function) @
ionic.bundle.js:18891
ionic.bundle.js:18891 Error: [$compile:ctreq] Controller 'ionSlideBox',
required by directive 'ionSlide', can't be found!
http://errors.angularjs.org/1.2.17/$compile/ctreq?p0=ionSlideBox&p1=ionSlide
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:9070:12
    at getControllers (
http://localhost:8100/lib/ionic/js/ionic.bundle.js:15428:19)
    at nodeLinkFn (
http://localhost:8100/lib/ionic/js/ionic.bundle.js:15600:35)
    at compositeLinkFn (
http://localhost:8100/lib/ionic/js/ionic.bundle.js:15003:15)
    at compositeLinkFn (
http://localhost:8100/lib/ionic/js/ionic.bundle.js:15006:13)
    at compositeLinkFn (
http://localhost:8100/lib/ionic/js/ionic.bundle.js:15006:13)
    at nodeLinkFn (
http://localhost:8100/lib/ionic/js/ionic.bundle.js:15593:24)
    at compositeLinkFn (
http://localhost:8100/lib/ionic/js/ionic.bundle.js:15003:15)
    at nodeLinkFn (
http://localhost:8100/lib/ionic/js/ionic.bundle.js:15593:24)
    at compositeLinkFn (
http://localhost:8100/lib/ionic/js/ionic.bundle.js:15003:15) <ion-slide
*ngfor="#slide of slides" class="slider-slide">(anonymous function) @
ionic.bundle.js:18891
2ionic.bundle.js:18891 Error: [$compile:ctreq] Controller 'ionSlideBox',
required by directive 'ionSlide', can't be found!
http://errors.angularjs.org/1.2.17/$compile/ctreq?p0=ionSlideBox&p1=ionSlide
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:9070:12
    at getControllers (
http://localhost:8100/lib/ionic/js/ionic.bundle.js:15428:19)
    at nodeLinkFn (
http://localhost:8100/lib/ionic/js/ionic.bundle.js:15600:35)
    at compositeLinkFn (
http://localhost:8100/lib/ionic/js/ionic.bundle.js:15003:15)
    at compositeLinkFn (
http://localhost:8100/lib/ionic/js/ionic.bundle.js:15006:13)
    at compositeLinkFn (
http://localhost:8100/lib/ionic/js/ionic.bundle.js:15006:13)
    at nodeLinkFn (
http://localhost:8100/lib/ionic/js/ionic.bundle.js:15593:24)
    at compositeLinkFn (
http://localhost:8100/lib/ionic/js/ionic.bundle.js:15003:15)
    at nodeLinkFn (
http://localhost:8100/lib/ionic/js/ionic.bundle.js:15593:24)
    at compositeLinkFn (
http://localhost:8100/lib/ionic/js/ionic.bundle.js:15003:15) <ion-slide
class="slider-slide">(anonymous function) @ ionic.bundle.js:18891
ionic.bundle.js:18891 Error: [$injector:unpr] Unknown provider:
$elementProvider <- $element
http://errors.angularjs.org/1.2.17/$injector/unpr?p0=%24elementProvider%20%3C-%20%24element
    at ionic.bundle.js:9070
    at ionic.bundle.js:12727
    at Object.getService [as get](ionic.bundle.js:12854)
    at ionic.bundle.js:12732
    at getService (ionic.bundle.js:12854)
    at invoke (ionic.bundle.js:12881)
    at Object.instantiate (ionic.bundle.js:12902)
    at ionic.bundle.js:16156
    at updateView (ionic.bundle.js:42695)
    at eventHook (ionic.bundle.js:42642)

Thanks in advance!!!!
Kind regards,

Sagar

2016-03-24 15:50 GMT+01:00 Meke Ladna notifications@github.com:

**Comment by ladmerc** [comment]
Hi Sagamang, I have made a couple of commits and updated the Readme. You mind pulling the code and trying again? I will get a codepen as soon as I get the chance to

**Comment by ladmerc** [comment]
UPDATE:

Here's the codepen I promised:
https://codepen.io/ladmerc/pen/JXNQXr

**Comment by Sagamang** [comment]
Sorry for the late reply,
I tried to implement it again after your commits, but it still does not seems to work.

**Comment by Sagamang** [comment]
My error according to the console now is: 

ionic.bundle.js:18891 Error: [$compile:multidir] Multiple directives [scrollToTop, scrollToTop] asking for 'scrollToTop' controller on: <ion-view class="class ng-enter pane" scroll-to-top="">
http://errors.angularjs.org/1.2.17/$compile/multidir?p0=scrollToTop&p1=scro…n-view%20class%3D%22class%20ng-enter%20pane%22%20scroll-to-top%3D%22%22%3E
    at ionic.bundle.js:9070
    at assertNoDuplicate (ionic.bundle.js:15837)
    at applyDirectivesToNode (ionic.bundle.js:15250)
    at compileNodes (ionic.bundle.js:14950)
    at compile (ionic.bundle.js:14883)
    at updateView (ionic.bundle.js:42688)
    at eventHook (ionic.bundle.js:42642)
    at Scope.$broadcast (ionic.bundle.js:21789)
    at $state.transition.resolved.then.$state.transition (ionic.bundle.js:35066)
    at wrappedCallback (ionic.bundle.js:20400)(anonymous function) @ ionic.bundle.js:18891

**Comment by ladmerc** [comment]
Hello Sagamang,
can you place your code in a codepen so I take a look?
Thanks 

```
On Monday, April 4, 2016 1:19 PM, Sagamang <notifications@github.com> wrote:
```

 My error according to the console now is: ionic.bundle.js:18891 Error: [$compile:multidir] Multiple directives [scrollToTop, scrollToTop] asking for 'scrollToTop' controller on: 
http://errors.angularjs.org/1.2.17/$compile/multidir?p0=scrollToTop&p1=scro…n-view%20class%3D%22class%20ng-enter%20pane%22%20scroll-to-top%3D%22%22%3E
 at ionic.bundle.js:9070
 at assertNoDuplicate (ionic.bundle.js:15837)
 at applyDirectivesToNode (ionic.bundle.js:15250)
 at compileNodes (ionic.bundle.js:14950)
 at compile (ionic.bundle.js:14883)
 at updateView (ionic.bundle.js:42688)
 at eventHook (ionic.bundle.js:42642)
 at Scope.$broadcast (ionic.bundle.js:21789)
 at $state.transition.resolved.then.$state.transition (ionic.bundle.js:35066)
 at wrappedCallback (ionic.bundle.js:20400)(anonymous function) @ ionic.bundle.js:18891—

**Comment by angelarted** [comment]
To me it worked perfectly as I inserted it in my code, nothing more to add or fix.
Yes, maybe it is better to view everything about Sagamang's code to be sure the error doesn't came from something else rather than the module itself.

**Comment by ladmerc** [comment]
I guess I can close this now. Recent commit should fix most issues.
